general {
        output_format = "i3bar"
        colors = true
        interval = 30
        separator = ""
}

order += "volume master"
order += "battery 1"
order += "tztime istanbul"

volume master {
        format = "|%volume"
        format_muted = "|MUTED"
        device = "default"
        mixer = "Master"
        mixer_idx = 0
        separator_block_width = 0
}

# battery 0 {
#         format = " |%percentage"
#         path = "/sys/class/power_supply/BAT0/uevent"
#         low_threshold = 10
#         separator_block_width = 0
# }

battery 1 {
        format = "|%percentage"
        path = "/sys/class/power_supply/BAT1/uevent"
        low_threshold = 10
        separator_block_width = 0
}

tztime istanbul {
        format = "|%H:%M|%Y-%m-%d|"
        timezone = "Europe/Istanbul"
}